Repository perfect-matching/perfectmatching-backend, pull requests merged in 2019-09, with the labels that each got.

#69 Added User 생성 및 Project 개설 Post 작성 및 이전 로직 Bug Fix.
  Project-Matching/gradle/wrapper/gradle-wrapper.properties
  Project-Matching/src/main/java/com/matching/AppRunner.java
  Project-Matching/src/main/java/com/matching/config/SecurityConfig.java
  Project-Matching/src/main/java/com/matching/config/auth/SecurityConstants.java
  Project-Matching/src/main/java/com/matching/config/filter/JwtAuthenticationFilter.java
  Project-Matching/src/main/java/com/matching/config/filter/JwtAuthorizationFilter.java
  Project-Matching/src/main/java/com/matching/config/handler/CustomLogoutSuccessHandler.java
  Project-Matching/src/main/java/com/matching/controller/ProjectController.java
  Project-Matching/src/main/java/com/matching/controller/RegisterController.java
  Project-Matching/src/main/java/com/matching/controller/TagController.java
  Project-Matching/src/main/java/com/matching/domain/JwtToken.java
  Project-Matching/src/main/java/com/matching/domain/Tag.java
  Project-Matching/src/main/java/com/matching/domain/User.java
  Project-Matching/src/main/java/com/matching/domain/UserProject.java
  Project-Matching/src/main/java/com/matching/domain/UserSkill.java
  Project-Matching/src/main/java/com/matching/domain/dto/DoneProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/UserDTO.java
  Project-Matching/src/main/java/com/matching/domain/enums/LocationType.java
  Project-Matching/src/main/java/com/matching/domain/enums/PositionType.java
  Project-Matching/src/main/java/com/matching/repository/TagRepository.java
  Project-Matching/src/main/java/com/matching/repository/UserRepository.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
  Project-Matching/src/main/java/com/matching/service/RegisterService.java
  Project-Matching/src/main/java/com/matching/service/TagService.java
  Project-Matching/src/test/java/com/matching/controller/CommentControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/DoneProjectControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/ProfileControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/ProjectControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/RegisterControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/TagControllerTest.java
  Project-Matching/src/test/java/com/matching/domain/JwtTokenTest.java
  Project-Matching/src/test/java/com/matching/domain/dto/UserDTOTest.java
  README.md
Labels: bug, documentation, enhancement

#72 파일 업로드를 위한 gitignore 정책 추가 및 JwtAuthenticationFilter 변경
  .gitignore
  Project-Matching/src/main/java/com/matching/config/filter/JwtAuthenticationFilter.java
Labels: enhancement

#73 REST API 데이터 폼 양식 변경.
  README.md
  documents/get.md
  documents/post.md
Labels: documentation, enhancement

#80 add file upload API
  Project-Matching/src/main/java/com/matching/config/FileConfig.java
  Project-Matching/src/main/java/com/matching/config/exception/FileDownloadException.java
  Project-Matching/src/main/java/com/matching/config/exception/FileUploadException.java
  Project-Matching/src/main/java/com/matching/controller/FileUploadController.java
  Project-Matching/src/main/java/com/matching/domain/FileUploadResponse.java
  Project-Matching/src/main/java/com/matching/service/FileUploadDownloadService.java
  README.md
Labels: enhancement

#78 Added Project와 Commnet 생성, 수정, 삭제 요청 로직 추가 및 클라이언트 쪽에서 발생한 버그Fix.
  Project-Matching/src/main/java/com/matching/config/SecurityConfig.java
  Project-Matching/src/main/java/com/matching/config/filter/JwtAuthenticationFilter.java
  Project-Matching/src/main/java/com/matching/config/filter/JwtAuthorizationFilter.java
  Project-Matching/src/main/java/com/matching/controller/CommentController.java
  Project-Matching/src/main/java/com/matching/controller/ProjectController.java
  Project-Matching/src/main/java/com/matching/domain/Project.java
  Project-Matching/src/main/java/com/matching/domain/Tag.java
  Project-Matching/src/main/java/com/matching/domain/User.java
  Project-Matching/src/main/java/com/matching/domain/dto/CommentDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/DoneProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/UserDTO.java
  Project-Matching/src/main/java/com/matching/repository/CommentRepository.java
  Project-Matching/src/main/java/com/matching/repository/ProjectRepository.java
  Project-Matching/src/main/java/com/matching/repository/ProjectTagRepository.java
  Project-Matching/src/main/java/com/matching/service/CommentService.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
  Project-Matching/src/main/java/com/matching/service/RegisterService.java
  Project-Matching/src/test/java/com/matching/controller/CommentControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/ProjectControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/RegisterControllerTest.java
  README.md
  documents/get.md
  documents/post.md
Labels: bug, documentation, enhancement

#81 modify README.md
  README.md
Labels: documentation

#82 edit README.md
  README.md
Labels: documentation

#84 add JwtResolver
  Project-Matching/src/main/java/com/matching/config/auth/JwtResolver.java
  Project-Matching/src/main/java/com/matching/service/CommentService.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
Labels: duplicate, enhancement

#90 Added Project 상세 로직 api, 프로젝트와 유저 매칭 로직 추가.
  Project-Matching/src/main/java/com/matching/config/HttpConfig.java
  Project-Matching/src/main/java/com/matching/config/SecurityConfig.java
  Project-Matching/src/main/java/com/matching/controller/ProfileController.java
  Project-Matching/src/main/java/com/matching/controller/ProjectController.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProcessingProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProjectApplyDTO.java
  Project-Matching/src/main/java/com/matching/domain/enums/LocationType.java
  Project-Matching/src/main/java/com/matching/domain/enums/PositionType.java
  Project-Matching/src/main/java/com/matching/repository/UserProjectRepository.java
  Project-Matching/src/main/java/com/matching/service/ProfileService.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
  Project-Matching/src/test/java/com/matching/controller/ProfileControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/ProjectControllerTest.java
  Project-Matching/src/test/java/com/matching/domain/dto/ProjectApplyDTOTest.java
  README.md
  documents/delete.md
  documents/get.md
  documents/post.md
  documents/put.md
Labels: bug, documentation, enhancement

#95 Added DoneProject 로직 추가 및 태그 데이터 셋 추가.
  .gitignore
  Project-Matching/src/main/java/com/matching/AppRunner.java
  Project-Matching/src/main/java/com/matching/config/SecurityConfig.java
  Project-Matching/src/main/java/com/matching/controller/DoneProjectController.java
  Project-Matching/src/main/java/com/matching/controller/ProjectController.java
  Project-Matching/src/main/java/com/matching/controller/RegisterController.java
  Project-Matching/src/main/java/com/matching/domain/DoneProject.java
  Project-Matching/src/main/java/com/matching/domain/docs/RestDocs.java
  Project-Matching/src/main/java/com/matching/domain/dto/DoneProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/enums/LocationType.java
  Project-Matching/src/main/java/com/matching/domain/enums/PositionType.java
  Project-Matching/src/main/java/com/matching/repository/DoneProjectRepository.java
  Project-Matching/src/main/java/com/matching/repository/UsedSkillRepository.java
  Project-Matching/src/main/java/com/matching/service/DoneProjectService.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
  Project-Matching/src/test/java/com/matching/controller/DoneProjectControllerTest.java
  README.md
  documents/delete.md
  documents/post.md
  documents/put.md
Labels: documentation, enhancement

#94 Refactor Response header for REST API
  Project-Matching/src/main/java/com/matching/controller/CommentController.java
  Project-Matching/src/main/java/com/matching/controller/DoneProjectController.java
  Project-Matching/src/main/java/com/matching/controller/FileController.java
  Project-Matching/src/main/java/com/matching/controller/ProfileController.java
  Project-Matching/src/main/java/com/matching/controller/ProjectController.java
  Project-Matching/src/main/java/com/matching/controller/RegisterController.java
  Project-Matching/src/main/java/com/matching/controller/TagController.java
  Project-Matching/src/main/java/com/matching/controller/UserController.java
  Project-Matching/src/main/java/com/matching/service/CommentService.java
  Project-Matching/src/main/java/com/matching/service/DoneProjectService.java
  Project-Matching/src/main/java/com/matching/service/ProfileService.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
  Project-Matching/src/main/java/com/matching/service/RegisterService.java
  Project-Matching/src/main/java/com/matching/service/TagService.java
  Project-Matching/src/test/java/com/matching/controller/CommentControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/DoneProjectControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/ProfileControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/ProjectControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/RegisterControllerTest.java
Labels: Refactoring, enhancement

#97 Added Project Tag 기반 필터링 검색 기능 추가.
  Project-Matching/src/main/java/com/matching/AppRunner.java
  Project-Matching/src/main/java/com/matching/controller/ProjectController.java
  Project-Matching/src/main/java/com/matching/domain/dto/CommentDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/DoneProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/MemberDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProcessingProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProfileDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProjectsDTO.java
  Project-Matching/src/main/java/com/matching/repository/ProjectRepository.java
  Project-Matching/src/main/java/com/matching/repository/ProjectTagRepository.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
  Project-Matching/src/test/java/com/matching/domain/dto/ProjectsDTOTest.java
  README.md
Labels: enhancement

#96 Modify file upload
  Project-Matching/src/main/java/com/matching/AppRunner.java
  Project-Matching/src/main/java/com/matching/config/SecurityConfig.java
  Project-Matching/src/main/java/com/matching/controller/FileController.java
  Project-Matching/src/main/java/com/matching/service/FileService.java
  Project-Matching/src/test/java/com/matching/controller/FileControllerTest.java
  documents/delete.md
  documents/get.md
  documents/put.md
Labels: Refactoring, documentation, enhancement

#98 Modify README.md
  README.md
Labels: documentation

#102 Added 프로젝트 지원자 목록 추가 및 Bug Fix.
  Project-Matching/src/main/java/com/matching/config/filter/JwtAuthenticationFilter.java
  Project-Matching/src/main/java/com/matching/controller/ProfileController.java
  Project-Matching/src/main/java/com/matching/domain/dto/DoneProjectDTO.java
  Project-Matching/src/main/java/com/matching/domain/dto/ProfileDTO.java
  Project-Matching/src/main/java/com/matching/repository/UserProjectRepository.java
  Project-Matching/src/main/java/com/matching/service/DoneProjectService.java
  Project-Matching/src/main/java/com/matching/service/ProfileService.java
  Project-Matching/src/main/java/com/matching/service/ProjectService.java
  Project-Matching/src/test/java/com/matching/controller/DoneProjectControllerTest.java
  Project-Matching/src/test/java/com/matching/controller/ProfileControllerTest.java
  README.md
  documents/get.md
  documents/post.md
  documents/put.md
Labels: bug, documentation, enhancement

#104 Modify /api/project/cancel/{idx} api 오탈자 수정.
  Project-Matching/src/main/java/com/matching/controller/ProjectController.java
Labels: bug
